// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	bot "github.com/es-debug/backend-academy-2024-go-template/pkg/api/http/v1/bot"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExternalClient is an autogenerated mock type for the ExternalClient type
type MockExternalClient struct {
	mock.Mock
}

type MockExternalClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExternalClient) EXPECT() *MockExternalClient_Expecter {
	return &MockExternalClient_Expecter{mock: &_m.Mock}
}

// UpdatesPost provides a mock function with given fields: ctx, request
func (_m *MockExternalClient) UpdatesPost(ctx context.Context, request *bot.LinkUpdate) (bot.UpdatesPostRes, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdatesPost")
	}

	var r0 bot.UpdatesPostRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bot.LinkUpdate) (bot.UpdatesPostRes, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bot.LinkUpdate) bot.UpdatesPostRes); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bot.UpdatesPostRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bot.LinkUpdate) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExternalClient_UpdatesPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatesPost'
type MockExternalClient_UpdatesPost_Call struct {
	*mock.Call
}

// UpdatesPost is a helper method to define mock.On call
//   - ctx context.Context
//   - request *bot.LinkUpdate
func (_e *MockExternalClient_Expecter) UpdatesPost(ctx interface{}, request interface{}) *MockExternalClient_UpdatesPost_Call {
	return &MockExternalClient_UpdatesPost_Call{Call: _e.mock.On("UpdatesPost", ctx, request)}
}

func (_c *MockExternalClient_UpdatesPost_Call) Run(run func(ctx context.Context, request *bot.LinkUpdate)) *MockExternalClient_UpdatesPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bot.LinkUpdate))
	})
	return _c
}

func (_c *MockExternalClient_UpdatesPost_Call) Return(_a0 bot.UpdatesPostRes, _a1 error) *MockExternalClient_UpdatesPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExternalClient_UpdatesPost_Call) RunAndReturn(run func(context.Context, *bot.LinkUpdate) (bot.UpdatesPostRes, error)) *MockExternalClient_UpdatesPost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExternalClient creates a new instance of MockExternalClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExternalClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExternalClient {
	mock := &MockExternalClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
