{
 "title": "Scrapper",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": "scrapper:14003" }
  ]
 },
 "panels": [
  {
   "title": "Business Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape time duration seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le,type) (rate(scrapper_scrape_duration_seconds_bucket[5m])))",
       "legendFormat": "P50 - {{type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le,type) (rate(scrapper_scrape_duration_seconds_bucket[5m])))",
       "legendFormat": "P95 - {{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le,type) (rate(scrapper_scrape_duration_seconds_bucket[5m])))",
       "legendFormat": "P99 - {{type}}"
      }
     ]
    },
    {
     "title": "Total requests in second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (status) (\r\n  rate(scrapper_http_requests_total[1m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests duration in second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(scrapper_http_requests_duration_seconds_bucket[5m])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(scrapper_http_requests_duration_seconds_bucket[5m])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(scrapper_http_requests_duration_seconds_bucket[5m])))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Active links total",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      { "expr": "scrapper_active_links_total", "legendFormat": "{{type}}" }
     ]
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"$app\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=\"$app\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=\"$app\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=\"$app\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"$app\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"$app\"}",
     "legendFormat": "go_memstats_gc_sys_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=\"$app\"} - go_memstats_other_sys_bytes{instance=\"$app\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"$app\"}",
     "legendFormat": "go_memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes" },
    { "expr": "go_memstats_heap_sys_bytes" },
    { "expr": "go_memstats_heap_idle_bytes" },
    { "expr": "go_memstats_heap_inuse_bytes" },
    {
     "expr": "go_memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_stack_inuse_bytes" },
    { "expr": "go_memstats_stack_sys_bytes" }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_sys_bytes" }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total - go_memstats_frees_total"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[1m])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "go_gc_duration_seconds" }
   ]
  }
 ]
}