with-expecter: true
filename: "{{.InterfaceName | snakecase}}_mock.go"
mockname: "Mock{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/tg/processor:
    config:
      dir: ./internal/application/tg/processor/mocks
    interfaces:
      Client:
      Cache:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/server/http/scrapper:
    config:
      dir: ./internal/application/server/http/scrapper/mocks
    interfaces:
      Repository:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/server/http/bot:
    config:
      dir: ./internal/application/server/http/bot/mocks
    interfaces:
      Repository:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/scheduler/bot:
    config:
      dir: ./internal/application/scheduler/bot/mocks
    interfaces:
      Repository:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/client/http/bot:
    config:
      dir: ./internal/application/client/http/bot/mocks
    interfaces:
      ExternalClient:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/client/http/scrapper:
    config:
      dir: ./internal/application/client/http/scrapper/mocks
    interfaces:
      ExternalClient:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/client/kafka:
    config:
      dir: ./internal/application/client/kafka/mocks
    interfaces:
      Repository:
  github.com/es-debug/backend-academy-2024-go-template/pkg/middleware/ratelimiter/repository:
    config:
      dir: ./pkg/middleware/ratelimiter/repository/mocks
    interfaces:
      Repository:
  github.com/es-debug/backend-academy-2024-go-template/internal/application/updater:
    config:
      dir: ./internal/application/updater/mocks
    interfaces:
      Handler:
