services:
  bot_migrator:
    image: golang:1.23.2
    container_name: bot_migrator
    working_dir: /app
    volumes:
      - ./:/app
    command: make migrate_bot
    depends_on:
      bot_postgres:
        condition: service_healthy
    networks:
      - app_network

  scrapper_migrator:
    image: golang:1.23.2
    container_name: scrapper_migrator
    working_dir: /app
    volumes:
      - ./:/app
    command: make migrate_scrapper
    depends_on:
      scrapper_postgres:
        condition: service_healthy
    networks:
      - app_network

  bot_postgres:
    container_name: bot_postgres
    hostname: bot_postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=bot
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5434
      - POSTGRES_SSL_MODE=disable
      - PGDATA=/data/postgres
    ports:
      - "5434:5434"
    volumes:
      - bot_postgres_data:/data/postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - app_network

  scrapper_postgres:
    container_name: scrapper_postgres
    hostname: scrapper_postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=scrapper
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
      - POSTGRES_SSL_MODE=disable
      - PGDATA=/data/postgres
    ports:
      - "5433:5433"
    volumes:
      - scrapper_postgres_data:/data/postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scrapper"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - app_network

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      bot_migrator:
        condition: service_completed_successfully
      bot_redis:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "8081:8081"

  scrapper:
    container_name: scrapper
    build:
      context: .
      dockerfile: Dockerfile.scrapper
    depends_on:
      scrapper_migrator:
        condition: service_completed_successfully
      scrapper_redis:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "8080:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      - app_network

  kafka1:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka1
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    networks:
      - app_network

  kafka2:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka2
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    networks:
      - app_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092
    restart: unless-stopped
    depends_on:
      kafka1:
        condition: service_started
      kafka2:
        condition: service_started
    networks:
      - app_network

  bot_redis:
    image: redis:7.0
    container_name: bot_redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - bot_redis_data:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]
    restart: unless-stopped
    networks:
      - app_network

  scrapper_redis:
    image: redis:7.0
    container_name: scrapper_redis
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - scrapper_redis_data:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]
    restart: unless-stopped
    networks:
      - app_network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      bot:
        condition: service_started
      scrapper:
        condition: service_started
    networks:
      - app_network
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards/default:/var/lib/grafana/dashboards/default:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  bot_postgres_data:
  scrapper_postgres_data:
  bot_redis_data:
  scrapper_redis_data:
  prometheus_data:
  grafana_data:
