// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/es-debug/backend-academy-2024-go-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteChat provides a mock function with given fields: chatID
func (_m *MockRepository) DeleteChat(chatID int64) error {
	ret := _m.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChat'
type MockRepository_DeleteChat_Call struct {
	*mock.Call
}

// DeleteChat is a helper method to define mock.On call
//   - chatID int64
func (_e *MockRepository_Expecter) DeleteChat(chatID interface{}) *MockRepository_DeleteChat_Call {
	return &MockRepository_DeleteChat_Call{Call: _e.mock.On("DeleteChat", chatID)}
}

func (_c *MockRepository_DeleteChat_Call) Run(run func(chatID int64)) *MockRepository_DeleteChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRepository_DeleteChat_Call) Return(_a0 error) *MockRepository_DeleteChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteChat_Call) RunAndReturn(run func(int64) error) *MockRepository_DeleteChat_Call {
	_c.Call.Return(run)
	return _c
}

// ListLinks provides a mock function with given fields: chatID
func (_m *MockRepository) ListLinks(chatID int64) ([]*domain.Link, error) {
	ret := _m.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for ListLinks")
	}

	var r0 []*domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]*domain.Link, error)); ok {
		return rf(chatID)
	}
	if rf, ok := ret.Get(0).(func(int64) []*domain.Link); ok {
		r0 = rf(chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLinks'
type MockRepository_ListLinks_Call struct {
	*mock.Call
}

// ListLinks is a helper method to define mock.On call
//   - chatID int64
func (_e *MockRepository_Expecter) ListLinks(chatID interface{}) *MockRepository_ListLinks_Call {
	return &MockRepository_ListLinks_Call{Call: _e.mock.On("ListLinks", chatID)}
}

func (_c *MockRepository_ListLinks_Call) Run(run func(chatID int64)) *MockRepository_ListLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRepository_ListLinks_Call) Return(_a0 []*domain.Link, _a1 error) *MockRepository_ListLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListLinks_Call) RunAndReturn(run func(int64) ([]*domain.Link, error)) *MockRepository_ListLinks_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterChat provides a mock function with given fields: chatID
func (_m *MockRepository) RegisterChat(chatID int64) error {
	ret := _m.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RegisterChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterChat'
type MockRepository_RegisterChat_Call struct {
	*mock.Call
}

// RegisterChat is a helper method to define mock.On call
//   - chatID int64
func (_e *MockRepository_Expecter) RegisterChat(chatID interface{}) *MockRepository_RegisterChat_Call {
	return &MockRepository_RegisterChat_Call{Call: _e.mock.On("RegisterChat", chatID)}
}

func (_c *MockRepository_RegisterChat_Call) Run(run func(chatID int64)) *MockRepository_RegisterChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRepository_RegisterChat_Call) Return(_a0 error) *MockRepository_RegisterChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RegisterChat_Call) RunAndReturn(run func(int64) error) *MockRepository_RegisterChat_Call {
	_c.Call.Return(run)
	return _c
}

// TrackLink provides a mock function with given fields: link
func (_m *MockRepository) TrackLink(link *domain.Link) (*domain.Link, error) {
	ret := _m.Called(link)

	if len(ret) == 0 {
		panic("no return value specified for TrackLink")
	}

	var r0 *domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Link) (*domain.Link, error)); ok {
		return rf(link)
	}
	if rf, ok := ret.Get(0).(func(*domain.Link) *domain.Link); ok {
		r0 = rf(link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Link) error); ok {
		r1 = rf(link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_TrackLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackLink'
type MockRepository_TrackLink_Call struct {
	*mock.Call
}

// TrackLink is a helper method to define mock.On call
//   - link *domain.Link
func (_e *MockRepository_Expecter) TrackLink(link interface{}) *MockRepository_TrackLink_Call {
	return &MockRepository_TrackLink_Call{Call: _e.mock.On("TrackLink", link)}
}

func (_c *MockRepository_TrackLink_Call) Run(run func(link *domain.Link)) *MockRepository_TrackLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Link))
	})
	return _c
}

func (_c *MockRepository_TrackLink_Call) Return(_a0 *domain.Link, _a1 error) *MockRepository_TrackLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_TrackLink_Call) RunAndReturn(run func(*domain.Link) (*domain.Link, error)) *MockRepository_TrackLink_Call {
	_c.Call.Return(run)
	return _c
}

// UntrackLink provides a mock function with given fields: chatID, url
func (_m *MockRepository) UntrackLink(chatID int64, url string) (*domain.Link, error) {
	ret := _m.Called(chatID, url)

	if len(ret) == 0 {
		panic("no return value specified for UntrackLink")
	}

	var r0 *domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (*domain.Link, error)); ok {
		return rf(chatID, url)
	}
	if rf, ok := ret.Get(0).(func(int64, string) *domain.Link); ok {
		r0 = rf(chatID, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(chatID, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UntrackLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UntrackLink'
type MockRepository_UntrackLink_Call struct {
	*mock.Call
}

// UntrackLink is a helper method to define mock.On call
//   - chatID int64
//   - url string
func (_e *MockRepository_Expecter) UntrackLink(chatID interface{}, url interface{}) *MockRepository_UntrackLink_Call {
	return &MockRepository_UntrackLink_Call{Call: _e.mock.On("UntrackLink", chatID, url)}
}

func (_c *MockRepository_UntrackLink_Call) Run(run func(chatID int64, url string)) *MockRepository_UntrackLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_UntrackLink_Call) Return(_a0 *domain.Link, _a1 error) *MockRepository_UntrackLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UntrackLink_Call) RunAndReturn(run func(int64, string) (*domain.Link, error)) *MockRepository_UntrackLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
