// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	repositorybot "github.com/es-debug/backend-academy-2024-go-template/internal/infrastructure/repository/bot"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddLink provides a mock function with given fields: chatID, link
func (_m *MockRepository) AddLink(chatID int64, link string) error {
	ret := _m.Called(chatID, link)

	if len(ret) == 0 {
		panic("no return value specified for AddLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = rf(chatID, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLink'
type MockRepository_AddLink_Call struct {
	*mock.Call
}

// AddLink is a helper method to define mock.On call
//   - chatID int64
//   - link string
func (_e *MockRepository_Expecter) AddLink(chatID interface{}, link interface{}) *MockRepository_AddLink_Call {
	return &MockRepository_AddLink_Call{Call: _e.mock.On("AddLink", chatID, link)}
}

func (_c *MockRepository_AddLink_Call) Run(run func(chatID int64, link string)) *MockRepository_AddLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_AddLink_Call) Return(_a0 error) *MockRepository_AddLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddLink_Call) RunAndReturn(run func(int64, string) error) *MockRepository_AddLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdates provides a mock function with no fields
func (_m *MockRepository) GetUpdates() ([]*repositorybot.UpdateChat, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpdates")
	}

	var r0 []*repositorybot.UpdateChat
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*repositorybot.UpdateChat, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*repositorybot.UpdateChat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repositorybot.UpdateChat)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdates'
type MockRepository_GetUpdates_Call struct {
	*mock.Call
}

// GetUpdates is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetUpdates() *MockRepository_GetUpdates_Call {
	return &MockRepository_GetUpdates_Call{Call: _e.mock.On("GetUpdates")}
}

func (_c *MockRepository_GetUpdates_Call) Run(run func()) *MockRepository_GetUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetUpdates_Call) Return(_a0 []*repositorybot.UpdateChat, _a1 error) *MockRepository_GetUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUpdates_Call) RunAndReturn(run func() ([]*repositorybot.UpdateChat, error)) *MockRepository_GetUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
