// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/es-debug/backend-academy-2024-go-template/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddUpdate provides a mock function with given fields: ctx, update
func (_m *MockRepository) AddUpdate(ctx context.Context, update *domain.Update) error {
	ret := _m.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for AddUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Update) error); ok {
		r0 = rf(ctx, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUpdate'
type MockRepository_AddUpdate_Call struct {
	*mock.Call
}

// AddUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - update *domain.Update
func (_e *MockRepository_Expecter) AddUpdate(ctx interface{}, update interface{}) *MockRepository_AddUpdate_Call {
	return &MockRepository_AddUpdate_Call{Call: _e.mock.On("AddUpdate", ctx, update)}
}

func (_c *MockRepository_AddUpdate_Call) Run(run func(ctx context.Context, update *domain.Update)) *MockRepository_AddUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Update))
	})
	return _c
}

func (_c *MockRepository_AddUpdate_Call) Return(_a0 error) *MockRepository_AddUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddUpdate_Call) RunAndReturn(run func(context.Context, *domain.Update) error) *MockRepository_AddUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
