// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/es-debug/backend-academy-2024-go-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// UpdatesPost provides a mock function with given fields: ctx, update
func (_m *MockHandler) UpdatesPost(ctx context.Context, update *domain.Update) error {
	ret := _m.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdatesPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Update) error); ok {
		r0 = rf(ctx, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandler_UpdatesPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatesPost'
type MockHandler_UpdatesPost_Call struct {
	*mock.Call
}

// UpdatesPost is a helper method to define mock.On call
//   - ctx context.Context
//   - update *domain.Update
func (_e *MockHandler_Expecter) UpdatesPost(ctx interface{}, update interface{}) *MockHandler_UpdatesPost_Call {
	return &MockHandler_UpdatesPost_Call{Call: _e.mock.On("UpdatesPost", ctx, update)}
}

func (_c *MockHandler_UpdatesPost_Call) Run(run func(ctx context.Context, update *domain.Update)) *MockHandler_UpdatesPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Update))
	})
	return _c
}

func (_c *MockHandler_UpdatesPost_Call) Return(_a0 error) *MockHandler_UpdatesPost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_UpdatesPost_Call) RunAndReturn(run func(context.Context, *domain.Update) error) *MockHandler_UpdatesPost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
