// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetActiveLinks provides a mock function with given fields: ctx
func (_m *MockRepository) GetActiveLinks(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveLinks")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetActiveLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveLinks'
type MockRepository_GetActiveLinks_Call struct {
	*mock.Call
}

// GetActiveLinks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetActiveLinks(ctx interface{}) *MockRepository_GetActiveLinks_Call {
	return &MockRepository_GetActiveLinks_Call{Call: _e.mock.On("GetActiveLinks", ctx)}
}

func (_c *MockRepository_GetActiveLinks_Call) Run(run func(ctx context.Context)) *MockRepository_GetActiveLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetActiveLinks_Call) Return(_a0 map[string]int, _a1 error) *MockRepository_GetActiveLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetActiveLinks_Call) RunAndReturn(run func(context.Context) (map[string]int, error)) *MockRepository_GetActiveLinks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
