app:
  terminate_timeout: 5s
bot:
  scrapper_url: http://localhost:8080
scrapper:
  url: localhost:8080
client:
  dial_timeout_seconds: 5s
  dial_keep_alive_seconds: 30s
  max_idle_conns: 100
  idle_conn_timeout_seconds: 90s
  tls_handshake_timeout_seconds: 10s
  expect_continue_timeout_seconds: 1s
  timeout: 30s
github:
scheduler:
  interval: 1h
