// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/es-debug/backend-academy-2024-go-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetAndClearUpdates provides a mock function with given fields: ctx, chatID
func (_m *MockRepository) GetAndClearUpdates(ctx context.Context, chatID int64) ([]*domain.Update, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetAndClearUpdates")
	}

	var r0 []*domain.Update
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.Update, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.Update); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Update)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAndClearUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndClearUpdates'
type MockRepository_GetAndClearUpdates_Call struct {
	*mock.Call
}

// GetAndClearUpdates is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockRepository_Expecter) GetAndClearUpdates(ctx interface{}, chatID interface{}) *MockRepository_GetAndClearUpdates_Call {
	return &MockRepository_GetAndClearUpdates_Call{Call: _e.mock.On("GetAndClearUpdates", ctx, chatID)}
}

func (_c *MockRepository_GetAndClearUpdates_Call) Run(run func(ctx context.Context, chatID int64)) *MockRepository_GetAndClearUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_GetAndClearUpdates_Call) Return(_a0 []*domain.Update, _a1 error) *MockRepository_GetAndClearUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAndClearUpdates_Call) RunAndReturn(run func(context.Context, int64) ([]*domain.Update, error)) *MockRepository_GetAndClearUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdatesChats provides a mock function with given fields: ctx
func (_m *MockRepository) GetUpdatesChats(ctx context.Context) ([]int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdatesChats")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUpdatesChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatesChats'
type MockRepository_GetUpdatesChats_Call struct {
	*mock.Call
}

// GetUpdatesChats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetUpdatesChats(ctx interface{}) *MockRepository_GetUpdatesChats_Call {
	return &MockRepository_GetUpdatesChats_Call{Call: _e.mock.On("GetUpdatesChats", ctx)}
}

func (_c *MockRepository_GetUpdatesChats_Call) Run(run func(ctx context.Context)) *MockRepository_GetUpdatesChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetUpdatesChats_Call) Return(_a0 []int64, _a1 error) *MockRepository_GetUpdatesChats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUpdatesChats_Call) RunAndReturn(run func(context.Context) ([]int64, error)) *MockRepository_GetUpdatesChats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
