name: Go CI & Docker Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build Go binaries
        run: |
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Test
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build bot image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.bot
          push: false
          tags: |
            bot:latest
            bot:${{ github.sha }}

      - name: Build scrapper image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.scrapper
          push: false
          tags: |
            scrapper:latest
            scrapper:${{ github.sha }}
